server {
    listen 443 ssl;
    server_name totally-legit-firmware-update.ctf.bzh;

    ssl_certificate     /etc/tls/server.crt;
    ssl_certificate_key /etc/tls/server.key;

    ssl_client_certificate /etc/tls/ca.crt;
    ssl_verify_client on;


    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;

        # Expose client certificate DN to backend/logs if needed
        add_header X-Client-DN $ssl_client_s_dn always;
    }
}
